const channels = document.querySelectorAll('.channel');
const chatWindow = document.getElementById('chat-window');
const channelData = {
    sigmasec: ['<i>Jul 08 02:26:46 &lt;rain&gt;</i> still looking for an rfi/lfi bot :p',
               '<i>Jul 08 02:28:30 &lt;pizzalover12&gt;</i> i&#39;ve got one N1ke :D with google bypass, if the bypass still works xD',
                   '<i>Jul 08 02:28:52 &lt;pizzalover12&gt;</i> but it&#39;s on a USB but i think the USB might be infected xD',
                   '<i>Jul 08 02:29:04 &lt;pizzalover12&gt;</i> so im scared to plug it in xD',
                   '<i>Jul 08 02:43:23 &lt;N1ke&gt;</i> found a critcal vulnnnn',
                   '<i>Jul 08 02:43:32 &lt;pwnjester&gt;</i> where',
                   '<i>Jul 08 02:43:35 &lt;N1ke&gt;</i> i was poking through capital one they have a code execution vuln',
                   '<i>Jul 08 02:43:38 &lt;N1ke&gt;</i> doesnt properly verify input',
                   '<i>Jul 08 02:44:45 &lt;N1ke&gt;</i> was thinking about ransomware but this is much better, with the de-salted and hashed username you can send any account money from anywhere :p',
                   '<i>Jul 08 02:44:50 &lt;pwnjester&gt;</i> AES tho',
                   '<i>Jul 08 02:44:59 &lt;N1ke&gt;</i> backup plan then',
                   '<i>Jul 08 02:45:03 &lt;N1ke&gt;</i> i need to build something, give me many hour',
               '<span class="join-message"><i>Jul 08 02:50:00 *** A1re has joined TIVSec</i></span>',
               '<i>Jul 08 02:58:43 &lt;pwnjester&gt;</i> bunch of idiots from tfnc callin us out for our opsec on /ras/',
                   '<i>Jul 08 02:58:46 &lt;pwnjester&gt;</i> nsa put a honeypot and one of us went down',
                   '<i>Jul 08 02:58:48 &lt;pwnjester&gt;</i> idk why they keep yappin about it',
                   '<i>Jul 08 03:13:18 &lt;Eden&gt;</i> well A) they are a bunch of dumbfucks, B) Jeffords is an retard who everyone would want to destroy, C) Apache 0day (pt2), D) Darren needs to be ass-whipped',
                   '<i>Jul 08 03:13:29 &lt;N1ke&gt;</i> E) bring the lols',
                   '<i>Jul 08 03:13:30 &lt;N1ke&gt;</i> :D',
                   '<i>Jul 08 03:13:35 &lt;Eden&gt;</i> yes, that too',
                   '<i>Jul 08 03:14:44 &lt;Eden&gt;</i> ah wait that was Adrian Chen sending us those insulting tweets',
                   '<i>Jul 08 03:14:47 &lt;Eden&gt;</i> both fucktards',
                   '<i>Jul 08 03:15:14 &lt;rain&gt;</i> i like C most',
                   '<i>Jul 08 03:15:15 &lt;rain&gt;</i> ;]',
                   '<i>Jul 08 03:15:17 &lt;Eden&gt;</i> he tried to arrange an interview with us, told him to gtfo before seclist gets rooted',
                   '<i>Jul 08 03:51:43 &lt;1andonlysalty&gt;</i> had palindrome look at the chase 0day, said we were a bunch of idiots',
                   '<i>Jul 08 03:51:47 &lt;1andonlysalty&gt;</i> wouldve been insulted if he was wrong',
                   '<i>Jul 08 03:51:53 &lt;rain&gt;</i> i still havent found anything in the ed irc',
                   '<i>Jul 08 03:51:54 &lt;rain&gt;</i> :(',
               '<i>Jul 08 06:22:10 &lt;1andonlysalty&gt;</i> wqant the most recent silent hawk emails too, fun lil story to read',
                   '<i>Jul 08 06:22:47 &lt;Eden&gt;</i> the stuff abt orlov?',
                   '<i>Jul 08 06:22:51 &lt;1andonlysalty&gt;</i> yuh',
                   '<i>Jul 08 08:54:59 &lt;rain&gt;</i> forgot to tell yguys',
                   '<i>Jul 08 08:55:05 &lt;rain&gt;</i> bought a flipper0',
                   '<i>Jul 08 08:55:12 &lt;rain&gt;</i> ready to 1337 it up',
                   '<i>Jul 08 11:02:42 &lt;N1ke&gt;</i> wheres palindrome?',
                   '<i>Jul 08 11:02:49 &lt;1andonlysalty&gt;</i> idk, hes busy with his bounties',
                   '<i>Jul 08 11:02:33 &lt;pwnjester&gt;</i> who had the old ddos for facebook',
                   '<i>Jul 08 14:03:44 &lt;N1ke&gt;</i> 4-6-2011 23:03:30  : SENT CONTROL [server]: \'PUSH_REQUEST\' (status=1)',
                   '<i>Jul 08 14:03:50 &lt;N1ke&gt;</i> after this',
                   '<i>Jul 08 14:03:54 &lt;N1ke&gt;</i> it just starts using an entire CPU core',
                   '<i>Jul 08 14:03:58 &lt;N1ke&gt;</i> crash things',
                   '<i>Jul 08 14:04:01 &lt;N1ke&gt;</i> use more and more memory',
                   '<i>Jul 08 14:04:04 &lt;N1ke&gt;</i> and not connect to the VPN',
                   '<i>Jul 08 14:04:06 &lt;pwnjester&gt;</i> thx',
                   '<i>Jul 08 14:10:02 &lt;rain&gt;</i> found an old dos script for roblox i wrote',
                   '<i>Jul 08 14:10:07 &lt;rain&gt;</i> uses my old malsec email, should work if you stick a loop on it',
                   '<i>Jul 08 14:10:13 &lt;rain&gt;</i> https://privnote.com/RAEcrsfu#1xi5vy9uY1',
                   '<i>Jul 08 14:10:19 &lt;rain&gt;</i> set the note to self destruct after 5 reads, should be enough',
                   '<i>Jul 08 14:10:52 &lt;1andonlysalty&gt;</i> doesnt delete the account, would only work once',
                   '<i>Jul 08 14:10:23 &lt;rain&gt;</i> oops, will fix later',
                   '<i>Jul 08 14:16:27 &lt;Eden&gt;</i> already sent kayla money for bots, sending Axl money for servers when he wants it',
                   '<i>Jul 08 14:16:30 &lt;Eden&gt;</i> we have 50000USD in donations',
                   '<i>Jul 08 14:16:36 &lt;pizzalover12&gt;</i> we have darkbaz to thank for most of it xD',
               '<i>Jul 08 14:27:26 &lt;Eden&gt;</i> everyone leave ED IRC',
                   '<i>Jul 08 14:27:35 &lt;Eden&gt;</i> this is serious, military hackers trying to hack us',
                   '<i>Jul 08 14:27:37 &lt;Eden&gt;</i> don&#39;t stay there',
                   '<i>Jul 08 14:28:17 &lt;pwnjester&gt;</i> i propose Operation:/R/aid',
                   '<i>Jul 08 14:28:23 &lt;pwnjester&gt;</i> we need .mil targets',
               '<i>Jul 08 14:28:33 &lt;pizzalover12&gt;</i> target #1 is pine gap',
                   '<i>Jul 08 14:28:36 &lt;pwnjester&gt;</i> salty, you have access to pine gap, yes?',
                   '<i>Jul 08 14:57:12 &lt;1andonlysalty&gt;</i> eventually, still no diplomatic ident',
                   '<i>Jul 08 14:57:17 &lt;1andonlysalty&gt;</i> getting it should take maybe a month',
                   '<i>Jul 08 15:31:03 &lt;pwnjester&gt;</i> any blueprints?',
                   '<i>Jul 08 15:44:10 &lt;1andonlysalty&gt;</i> again, a month',
                   '<i>Jul 08 15:44:12 &lt;pwnjester&gt;</i> k',
                   '<i>Jul 08 15:44:18 &lt;pwnjester&gt;</i> we wanna strike now, with no ident we can maybe crash the network remotely',
               '<span class="leave-message"><i>Jul 08 02:50:00 * 1andonlysalty has banned rain from TIVSec</i></span>',
                   '<i>Jul 08 15:44:20 &lt;1andonlysalty&gt;</i> skid, we just cant have wannabes for this',
                   '<i>Jul 08 15:44:26 &lt;pwnjester&gt;</i> yeah, youre good',
                   '<i>Jul 08 15:44:31 &lt;1andonlysalty&gt;</i> we should just try to copy what we can and keep all that info, crashing servers is just a temp inconvenience',
                   '<i>Jul 08 15:44:35 &lt;1andonlysalty&gt;</i> alr im gonna sleep, you get henry on the line, i want his hardware and whatnot',
               '<i>Jul 08 15:47:30 &lt;Eden&gt;</i> I’ll see what Darkbaz sells, we want pis, flippers, hard drives, cds and we’ll get weapons later when we finish figuring everything out',
                   '<i>Jul 08 16:58:12 &lt;pwnjester&gt;</i> i’ll add a few people here who can help',
                   '<i>Jul 08 16:58:13 &lt;pwnjester&gt;</i> in the meantime',
                   '<i>Jul 08 16:58:13 &lt;pwnjester&gt;</i> everyone, gather tools (hardware/software), gather people you can trust and get to planning, i want maps drawn and people fucking working',
                   '<i>Jul 08 18:07:42 &lt;Eden&gt;</i> Bought 7 flippers, have enough storage for roughly 70 terabytes, have a discount deal for anthrax',
               '<span class="join-message"><i>Jul 08 20:11:01 *** xyro has joined TIVSec</i></span>',
               '<span class="join-message"><i>Jul 08 22:49:22 *** iwantarimjob has joined TIVSec</i></span>',
               '<span class="join-message"><i>Jul 08 23:55:59 *** Tamyska has joined TIVSec</i></span>',
               '<i>Jul 09 01:03:06 &lt;1andonlysalty&gt;</i> mornin fucks',
                   '<i>Jul 09 01:24:00 &lt;pwnjester&gt;</i> lets make a list',
                   '<i>Jul 09 01:24:02 &lt;pwnjester&gt;</i> todo list',
                   '<i>Jul 09 01:24:13 &lt;pwnjester&gt;</i> 1) plan 2) inventory 3) operation date 4) fuckin do it',
                   '<i>Jul 09 01:39:56 &lt;iwantarimjob&gt;</i> what is happening',
                   '<i>Jul 09 01:40:34 &lt;1andonlysalty&gt;</i> haxoring is happening',
                   '<i>Jul 09 04:32:06 &lt;pwnjester&gt;</i> ok i have some kind of a plan',
                   '<i>Jul 09 04:32:23 &lt;pwnjester&gt;</i> coordinated attacks. we hit frankfurt, pine gap, tons of other black sites',
                   '<i>Jul 09 04:32:31 &lt;pwnjester&gt;</i> we have an australian, we have ppl in several countries',
                   '<i>Jul 09 04:32:37 &lt;pwnjester&gt;</i> more onsite kind of hacks can be done',
                   '<i>Jul 09 07:11:45 &lt;1andonlysalty&gt;</i> i agree, i think we could at least access their network. pine gap is gonna be more fucked though',
                   '<i>Jul 09 08:01:36 &lt;xyro&gt;</i> pine gap is difficult as well as several others, the black sites under embassy covers are much easier to get to',
                   '<i>Jul 09 08:01:43 &lt;xyro&gt;</i> when the security of something is secrecy, its a joke',
                   '<i>Jul 09 08:01:43 &lt;xyro&gt;</i> anyone could hack them',
                   '<i>Jul 09 10:59:12 &lt;1andonlysalty&gt;</i> so we target embassies only?',
                   '<i>Jul 09 10:59:16 &lt;1andonlysalty&gt;</i> also xyro, im gonna add the other xyro so use your alt name',
                   '<span class="change-message"><i>Jul 09 11:02:33 ** xyro is now known as Marethyu</i></span>',
                   '<i>Jul 09 11:04:11 &lt;1andonlysalty&gt;</i> tyyy',
                   '<i>Jul 09 11:21:43 &lt;pwnjester&gt;</i> Eden is gonna be without wifi for the next few days, he\'ll still be working through some plans and ideas',
                   '<i>Jul 09 11:22:06 &lt;1andonlysalty&gt;</i> k',
                   '<span class="leave-message"><i>Jul 09 11:25:17 * Eden has disconnected from TIVSec</i></span>',
                   '<i>Jul 09 11:25:23 &lt;1andonlysalty&gt;</i> adios eden',
                   '<i>Jul 09 11:25:29 &lt;1andonlysalty&gt;</i> alr, time to play to strengths',
                   '<i>Jul 09 11:25:32 &lt;1andonlysalty&gt;</i> i have roles for everyone',
                   '<i>Jul 09 11:25:46 &lt;1andonlysalty&gt;</i> tamyska, hardware and resources (ik youre connected with the gov a little too much to help a ton, so do whatchu can)',
                   '<i>Jul 09 11:25:57 &lt;1andonlysalty&gt;</i> N1ke, check de .gov sites for vulns, i want the sites rooted when we do this',
                   '<i>Jul 09 11:26:01 &lt;1andonlysalty&gt;</i> pwnjester, recruit recruit recruit and then work with rim on payloads for everything that might be nice',
                   '<i>Jul 09 11:26:13 &lt;1andonlysalty&gt;</i> rim, payloads, config flippers and pis, i want car hacking (hotwire/unlock), i want rewiring tempuratures, i want more useful shit that i cant think of',
                   '<i>Jul 09 11:26:19 &lt;1andonlysalty&gt;</i> my retarded ass will get vault 9 tools ready, vermin, phone microph, traffick monitor for network, yadda yadda',
                   '<i>Jul 09 11:26:22 &lt;1andonlysalty&gt;</i> say yes mommy to confirm you understand',
                   '<i>Jul 09 11:33:31 &lt;pwnjester&gt;</i> got it (absolutely not)',
                   '<i>Jul 09 13:32:41 &lt;iwantarimjob&gt;</i> lmao, i understand',
                   '<i>Jul 09 16:42:13 &lt;Marethyu&gt;</i> and me?',
                   '<i>Jul 09 18:10:30 &lt;N1ke&gt;</i> sure, is there any specific way i should go about it?',
                   '<span class="join-message"><i>Jul 09 22:18:50 *** !xyro has joined TIVSec</i></span>',
                   '<i>Jul 10 02:28:00 &lt;1andonlysalty&gt;</i> n1ke, no you can do it any way you\'d like just make sure you\'ll still have root access whenever we decide to go with the op',
                   '<i>Jul 10 02:28:31 &lt;1andonlysalty&gt;</i> marethyu, do what you do best, gather locations, weak links in physical sec (youll be our intel)',
                   '<i>Jul 10 02:50:12 &lt;N1ke&gt;</i> 👍',
                   '<span class="leave-message"><i>Jul 10 05:08:19 * !xyro has quit TIVSec</i></span>',
                   '<i>Jul 10 05:43:02 &lt;1andonlysalty&gt;</i> what the fuckkkkkk',
                   '<i>Jul 10 08:52:46 &lt;iwantarimjob&gt;</i> i finished the flipper zero car key, when the ones that eden sent arrive i\'ll have 8 copies of the universal car keys',
                   '<i>Jul 10 09:00:21 &lt;1andonlysalty&gt;</i> yayyy',
                   '<span class="change-message"><i>Jul 10 09:01:19 ** 1andonlysalty is now known as Zoe</i></span>',
                   '<i>Jul 10 13:31:27 &lt;N1ke&gt;</i> ive found a few vulns, can\'t root anything yet',
                   '<i>Jul 10 14:03:16 &lt;Zoe&gt;</i> keep tryin',
                   '<i>Jul 10 21:58:20 &lt;Zoe&gt;</i> vermin is almost done, just havin someone do tests on it, keep it up ppls',
                   '<i>Jul 11 00:09:11 &lt;pwnjester&gt;</i> should be two more people coming in',
                   '<i>Jul 11 00:57:01 &lt;Zoe&gt;</i> yippie',
                   '<i>Jul 11 00:57:18 &lt;Zoe&gt;</i> marethyu, wbu, watchu found',
                   '<i>Jul 11 12:19:01 &lt;Marethyu&gt;</i> i can get three people into pine gap',
                   '<i>Jul 11 13:36:27 &lt;pwnjester&gt;</i> holy fuck',
                    '<i>Jul 11 16:00:22 &lt;Saltine&gt;</i> wait how',
                    '<i>Jul 11 22:48:10 &lt;Marethyu&gt;</i> they check the two main paths, top and bottom (if you look at it that way), thats where all identification checking is and most security. They have australians that handle identification checking and security at those top and bottom checkpoints, the americans are down the roads at the actual facility.',
                    '<i>Jul 11 22:48:14 &lt;Marethyu&gt;</i> those roads are used by all personnel.',
                    '<i>Jul 11 22:48:25 &lt;Marethyu&gt;</i> there are obviously the ideas of going in through the sides, but the security does surround the outside as well and anything going that direction will be shot without question, meaning getting in through the side would actively be harder',
                    '<i>Jul 11 22:48:31 &lt;Marethyu&gt;</i> this is the map i found on google: https://live-production.wcms.abc-cdn.net.au/9cbc21a216ba32e5db799bb840a117f2',
                    '<i>Jul 11 22:48:42 &lt;Marethyu&gt;</i> you can see the path that goes up and down, the security takes place really far away, slightly out of frame in that image, because the cia uses the field for all their stuff',
                    '<i>Jul 11 22:48:48 &lt;Marethyu&gt;</i> the lack of trees makes it impossible to sneak without security seeing you',
                    '<i>Jul 12 00:18:19 &lt;stoner_with_a_boner&gt;</i> satellite hacking',
                    '<i>Jul 12 03:28:35 &lt;Saltine&gt;</i> mf just listed the problems and provided 0 solutions',
                    '<i>Jul 12 03:28:41 &lt;Saltine&gt;</i> the feds caught him before he could finish lol',
                    '<i>Jul 12 03:31:02 &lt;Saltine&gt;</i> whatchu do stoner?',
                    '<i>Jul 12 05:07:46 &lt;stoner_with_a_boner&gt;</i> satellite hacking',
                    '<i>Jul 12 08:55:34 &lt;Saltine&gt;</i> perfecttttt',
                    '<i>Jul 12 08:55:45 &lt;Saltine&gt;</i> go dark for the day everyone, stoner needs to figure shit out but everyone else knows what to do',
                    '<i>Jul 12 08:55:46 &lt;Saltine&gt;</i> adios'
               ],
    offtopic: ['<i>Jul 08 09:31:06 &lt;1andonlysalty&gt;</i> aint nobody ever talked in here',
               '<i>Jul 09 01:22:44 &lt;rain&gt;</i> lol',
              ],
};

function updateChatWindow(channel) {
    chatWindow.innerHTML = '';
    channelData[channel].forEach(message => {
        const messageElement = document.createElement('p');
        messageElement.innerHTML = message;
        chatWindow.appendChild(messageElement);
        chatWindow.scrollTop = chatWindow.scrollHeight; // Scroll to bottom auto
    });
}

channels.forEach(channel => {
    channel.addEventListener('click', () => {
        document.querySelector('.channel.active').classList.remove('active');
        channel.classList.add('active');
        const channelName = channel.getAttribute('data-channel');
        document.querySelector('.tab-bar span').textContent = `#${channelName} [12] [+nt]: %% %% %% Verified member chat`;
        updateChatWindow(channelName);
    });
});

// Initial display
document.querySelector('.channel.active').classList.add('active');
document.querySelector('.tab-bar span').textContent = '#sigmasec  [12] [+nt]: %% %% %% Verified member chat';
updateChatWindow('sigmasec');
